export const COURSES_IS_LOADING = "COURSES_IS_LOADING";
export const COURSES_ADDED = "COURSES_ADDED";
export const COURSES_REMOVED = "COURSES_REMOVED";
//export const COURSES_RECEIVED = "COURSES_RECEIVED";
export const COURSES_SET_ERRORED = "COURSES_SET_ERRORED";
